# Generated by Django 4.0.8 on 2022-11-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tr_get3BData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSTIN', models.CharField(blank=True, max_length=200, null=True)),
                ('ReturnPeriod', models.CharField(blank=True, max_length=200, null=True)),
                ('Three_BTable', models.CharField(blank=True, max_length=200, null=True)),
                ('NatureOfSupplyType', models.CharField(blank=True, max_length=200, null=True)),
                ('TaxableValue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('IGSTAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('CGSTAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('SGSTAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('CESSAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('POS', models.CharField(blank=True, max_length=200, null=True)),
                ('InterStateSupplies', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('IntraStateSupplies', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('LiablityLedgerID', models.CharField(blank=True, max_length=200, null=True)),
                ('LiablityReturnPeriod', models.CharField(blank=True, max_length=200, null=True)),
                ('TransactionType', models.CharField(blank=True, max_length=200, null=True)),
                ('IGSTInterest', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('IGSTFee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('CGSTInterest', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('CGSTFee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('SGSTInterest', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('SGSTFee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('CESSInterest', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('CESSFee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('IGSTPaidAsCGST', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('IGSTPaidAsSGST', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('CGSTPaidAsIGST', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('SGSTPaidAsIGST', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Raw3b_ID', models.IntegerField(null=True)),
                ('CreatedOn', models.DateTimeField(auto_now=True)),
                ('IsActive', models.BooleanField(default=False)),
                ('DeletedOn', models.DateTimeField(null=True)),
                ('FP', models.CharField(blank=True, max_length=200, null=True)),
                ('SyncID', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tr_gstr2b_itcsumm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('fp', models.CharField(blank=True, max_length=50, null=True)),
                ('summ_type', models.CharField(blank=True, max_length=50, null=True)),
                ('supply_type', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_category', models.CharField(blank=True, max_length=50, null=True)),
                ('summary_igst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('summary_cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('summary_sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('summary_cess', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tr_igst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tr_cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tr_sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tr_cess', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('TableName2B', models.CharField(blank=True, max_length=50, null=True)),
                ('TableName3B', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=50, null=True)),
                ('row_version', models.DateTimeField(null=True)),
                ('CreatedOn', models.DateTimeField(auto_now=True)),
                ('SyncID', models.IntegerField(blank=True, null=True)),
                ('fpNew', models.DateField(null=True)),
            ],
        ),
    ]
