# Generated by Django 4.0.8 on 2022-11-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tr_get3bdata',
            table='tr_get3BData',
        ),
    ]
