# Generated by Django 4.0.8 on 2022-11-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tr_get3bdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tr_gstr2b_itcsumm',
            table='tr_gstr2b_itcsumm',
        ),
    ]
